name: grow_microfinance_app
description: Flutter mobile app for Grow Microfinance.
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.2
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  file_picker: ^6.1.1

flutter:
  uses-material-design: true
